language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - cd latest

script:
  - npm deploy

notifications:
  email:
    on_failure: change
    on_success: change