language: node_js
node_js:
  - "8"

script: 
  - npm install && npm run deploy:ci

#deploy:
#  provider: npm
#  email: marcel@ring-mail.at
#  api_key: $NPM_TOKEN
#  on:
#    tags: true
#    branch: master