language: node_js
node_js:
  - "8"

script: 
  - cd latest && npm install && npm run deploy
  - cd ../

deploy:
  provider: pages
  verbose: true
  local_dir: deploy
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    branch: website